// Generated by make_lang.py

LangDef lang_table[10] = {
  { "en_US", { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", } }, // 0 = English
  { "fr_FR", { "Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", } }, // 1 = French
  { "it_IT", { "Dom", "Lun", "Mar", "Mer", "Gio", "Ven", "Sab", } }, // 2 = Italian
  { "es_ES", { "Dom", "Lun", "Mar", "\x4d\x69\xc3\xa9", "Jue", "Vie", "\x53\xc3\xa1\x62", } }, // 3 = Spanish
  { "pt_PT", { "Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "\x53\xc3\xa1\x62", } }, // 4 = Portuguese
  { "de_DE", { "So", "Mo", "Di", "Mi", "Do", "Fr", "Sa", } }, // 5 = German
  { "nl_NL", { "Zo", "Ma", "Di", "Wo", "Do", "Vr", "Za", } }, // 6 = Dutch
  { "da_DK", { "\x53\xc3\xb8\x6e", "Man", "Tir", "Ons", "Tor", "Fre", "\x4c\xc3\xb8\x72", } }, // 7 = Danish
  { "sv_SE", { "\x53\xc3\xb6\x6e", "\x4d\xc3\xa5\x6e", "Tis", "Ons", "Tor", "Fre", "\x4c\xc3\xb6\x72", } }, // 8 = Swedish
  { "is_IS", { "Sun", "\x4d\xc3\xa1\x6e", "\xc3\x9e\x72\x69", "\x4d\x69\xc3\xb0", "Fim", "\x46\xc3\xb6\x73", "Lau", } }, // 9 = Icelandic
};

int num_langs = 10;

